marine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sea/', include('sea.urls')),
]

sea/urls.py
from django.urls import path
from . import views

app_name = 'sea'
urlpatterns = [
    path('', views.index, name='index'),

    path('yote', views.records, name='yote'),
    path('think', views.query2, name='think'),
    path('stuffs', views.query3, name='stuffs'),
    path('lastone', views.query13, name='lastone'),
    path('input', views.query4, name='input'),
    path('input1', views.query5, name='input1'),
    path('input2', views.query6, name='input2'),
    path('input3', views.query7, name='input3'),
    path('input4', views.query8, name='input4'),
    path('input5', views.query9, name='input5'),
    path('input6', views.query10, name='input6'),
    path('input7', views.query11, name='input7'),
    path('delete', views.query12, name='delete')
]

sea/models.py
from django.db import models

class BenthicSurvey_Data(models.Model):
    Enter_transect_ID = models.IntegerField()
    Enter_benthic_category = models.CharField(max_length=20)
    Enter_total_cover = models.IntegerField()


class FishSurvey_data(models.Model):
    ID = models.IntegerField(primary_key=True)
    Trans_ID = models.IntegerField()
    Name_Local = models.CharField(max_length=20)
    Total_Count = models.IntegerField()

class Invert_Data(models.Model):
    TransID = models.IntegerField()
    Name_Invert = models.CharField(max_length=20)
    No_Invert = models.IntegerField()
    
class Lookup_Benthic(models.Model):
    Name_Local = models.CharField(max_length=30)
    Abbrv = models.CharField(max_length=5)
    Name_Common = models.CharField(max_length=30)
    ID = models.IntegerField(primary_key=True)
    
class Lookup_Fish(models.Model):
    Name_Local = models.CharField(max_length=30)
    Name_Common = models.CharField(max_length=30)
    ID = models.IntegerField(primary_key=True)
    Scientific_N = models.CharField(max_length=30)
 
class Lookup_Invert(models.Model):
    Name_Local = models.CharField(max_length=30)
    Name_Common = models.CharField(max_length=30)
    ID = models.IntegerField(primary_key=True)
    
class Lookup_Site(models.Model):   
    SiteName = models.CharField(max_length=20)
    ID = models.IntegerField(primary_key=True)
    GPS_X = models.IntegerField()
    GPS_Y = models.IntegerField()
    
    def __str__(self):
        return self.SiteName
    
class Survey_Info(models.Model):
    TransID = models.IntegerField(primary_key=True)
    Name_Data_Collector = models.CharField(max_length=30)
    Site_Name = models.CharField(max_length=20)
    Trans_No = models.IntegerField()
    Date_Survey = models.DateTimeField('date surveyed')
    
#Report models.
class Average_fish_density(models.Model):
    Name_Local = models.CharField(max_length=30)
    AvgOf_Total_Count = models.FloatField()


class Average_fish_density_persite_allyears(models.Model):
    SiteName = models.CharField(max_length=20)
    Local_Name = models.CharField(max_length=20)
    AvgOf_Total_Cover = models.FloatField()


class Annual_average_fish_density_persite(models.Model):
    SiteName = models.CharField(max_length=20)
    Date_Survey = models.DateTimeField('date surveyed')
    Name_Local = models.CharField(max_length=30)
    Total_Count = models.IntegerField()
     
     
     

class Average_benthic_cover(models.Model):
    Enter_benthic_category = models.CharField(max_length=20)
    Avg_Of_Cover = models.FloatField()


class Average_benthic_cover_persite_allyears(models.Model):
    SiteName = models.CharField(max_length=20)
    Enter_benthic_category = models.CharField(max_length=20)
    Avg_Of_Cover = models.FloatField()


class Annual_average_benthic_cover_persite(models.Model):
    SiteName = models.CharField(max_length=20)
    Date_Survey = models.DateTimeField('date surveyed')   
    Enter_benthic_category = models.CharField(max_length=20)
    Avg_Of_Cover = models.FloatField()


class Average_invertebrates_cover(models.Model):
    Name_Invert = models.CharField(max_length=20)
    AvgOf_No_Invert = models.FloatField()


class Average_invertebrates_cover_persite_allyears(models.Model):
    SiteName = models.CharField(max_length=20)
    Date_Survey = models.DateTimeField('date surveyed')
    FirstOf_Name_Invert = models.CharField(max_length=30)
    SumOf_No_Invert = models.IntegerField()
    AvgOf_No_Invert = models.FloatField()


class Annual_average_invertebrate_cover_persite(models.Model):
    SiteName = models.CharField(max_length=20)
    Date_Survey = models.DateTimeField('date surveyed')
    FirstOf_Name_Invert = models.CharField(max_length=30)
    AvgOf_No_Invert = models.FloatField()
    

#overall fish records with averages per fish type per site.
# class Overall_fishrecords(models.Model):
#     pass

#overall invertebrate data with % per year per invert per site.
# class Overall_invertebrate_data(models.Model):
#     pass

sea/views.py
from django.shortcuts import render,render_to_response
from .models import Lookup_Site, Lookup_Fish,Survey_Info, Lookup_Invert,Invert_Data, Lookup_Benthic, BenthicSurvey_Data, FishSurvey_data
from django.forms import ModelForm
from django.template import RequestContext

def index(request):
    context = {
        
    }
    return render(request,'sea/index.html',context)
    
def records(request):
    yote  = Lookup_Site.objects.all()
    context = { 
        'yote':yote
    }
    return render(request,'sea/all.html',context)

def query2(request):
    items = Lookup_Site.objects.all()
    think = Lookup_Fish.objects.all()
    context = {
        'items':items,
        'think':think
    }
    return render(request,'sea/fikiri.html',context)
def query3(request):
    stuffs  = Lookup_Site.objects.all()
    listen = Lookup_Invert.objects.all()
    context = {
        'stuffs':stuffs,
        'listen':listen
    }
    return render(request,'sea/skiza.html',context)
def query13(request):
    lastone  = Lookup_Benthic.objects.all()
    balls = Lookup_Site.objects.all()
    context = {
        'lastone':lastone,
        'balls':balls
    }
    return render(request,'sea/phone.html',context)

class Lookup_FishForm(ModelForm):
    class Meta:
        model = Lookup_Fish
        fields = ['Name_Local', 'Name_Common','ID'] 
def query4(request, template_name='sea/input.html'):
    trial  = Lookup_Fish.objects.all()
    form = Lookup_FishForm(request.POST or None)
    if form.is_valid():
        form.save()
    # elif form.is_valid() and request.method == "POST" :
    #     item_id = request.POST.get(Lookup_FishForm, 'Name_Local')
    #     item = Lookup_Fish.objects.get(id=item_id)
    #     item.delete()
    context = {
        'trial':trial,
        'form':form
        }
    return render(request, template_name, context)

# def query12(request, pk, template_name='sea/input.html'):
#     form = Lookup_FishForm(request.POST or None)
#     fine= get_object_or_404(Lookup_Fish, Name_Local=pk)   
#     # fine  = Lookup_Fish.objects.all() 
#     if request.method=='POST':
#         form.delete()
#         return redirect('input')
#     context = {
#         'fine':fine,
#         'form':form
#     }
#     return render(request, template_name, context)
    
    
def query12(request, template_name='sea/input.html'):
    fine  = Lookup_Fish.objects.all()
    form = Lookup_FishForm(request.POST or None)
    if form.is_valid() and request.method == 'POST':
        item_id = int(request.POST.get('Name_Local'))
        item = Lookup_Fish.objects.get(id=item_id)
        item.delete()
    context = {
        'fine':fine,
        'form':form
        }
    return render(request, template_name, context)

# def query12(request):
#     form = Lookup_FishForm()
#     fine = Lookup_Fish.objects.all()
#     if request.method == 'POST':
#         item_id = int(request.POST.get('item_id'))  
#         item = Lookup_Fish.objects.get(id=item_id)       
#         item.delete()
#     return render(request, template_name, context)

class Lookup_InvertForm(ModelForm):
    class Meta:
        model = Lookup_Invert
        fields = ['Name_Local', 'Name_Common','ID'] 
def query5(request, template_name='sea/input1.html'):
    trial1  = Lookup_Invert.objects.all()
    form = Lookup_InvertForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'trial1':trial1,
        'form':form
        }
     
    return render(request, template_name, context)

class Lookup_BenthicForm(ModelForm):
    class Meta:
        model = Lookup_Benthic
        fields = '__all__'
def query6(request, template_name='sea/input2.html'):
    trial2  = Lookup_Benthic.objects.all()
    form = Lookup_BenthicForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'trial2':trial2,
        'form':form
        }
    return render(request, template_name, context)

class BenthicSurvey_DataForm(ModelForm):
    class Meta:
        model = BenthicSurvey_Data
        fields = '__all__'
def query7(request, template_name='sea/input3.html'):
    trial3  = BenthicSurvey_Data.objects.all()
    form = BenthicSurvey_DataForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'trial3':trial3,
        'form':form
        }
    return render(request, template_name, context)

class FishSurvey_dataForm(ModelForm):
    class Meta:
        model = FishSurvey_data
        fields = '__all__'
def query8(request, template_name='sea/input4.html'):
    trial4  = FishSurvey_data.objects.all()
    form = FishSurvey_dataForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'trial4':trial4,
        'form':form
        }
    return render(request, template_name, context)

class Invert_DataForm(ModelForm):
    class Meta:
        model = Invert_Data
        fields = ['TransID','Name_Invert','No_Invert']
def query9(request, template_name='sea/input5.html'):
    trial5  = Invert_Data.objects.all()
    form = Invert_DataForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'trial5':trial5,
        'form':form
        }
     
    return render(request, template_name, context)

class Lookup_SiteForm(ModelForm):
    class Meta:
        model = Lookup_Site
        fields = '__all__'
def query10(request, template_name='sea/input6.html'):
    trial6  = Lookup_Site.objects.all()
    form = Lookup_SiteForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'trial6':trial6,
        'form':form
        }
     
    return render(request, template_name, context)

class Survey_InfoForm(ModelForm):
    class Meta:
        model = Survey_Info
        fields = '__all__'
def query11(request, template_name='sea/input7.html'):
    trial7  = Survey_Info.objects.all()
    form = Survey_InfoForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'trial7':trial7,
        'form':form
        }
    return render(request, template_name, context)


        

templates/sea/all.html
<!--{{ yote }}-->

<table style="margin-left:50px">
    <thead>
        <tr>
            <th>Lookup ID</th>
            <th>Lookup GPS_x</th>
            <th>Lookup GPS_Y</th>
            <th>Lookup SiteName</th>
        </tr>
    </thead>
    <tbody>
        {% for i in yote %}
        <tr>
            <td>{{ i.ID }}</td>
            <td>{{ i.GPS_X }}</td>
            <td>{{ i.GPS_Y}}</td>
            <td>{{ i.SiteName }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/sea/delete.html
<!-- {{fine}} -->
<table>
    {% csrf_token %} {% for item in fine %}
    <tr class="datarow">
        <td>{{item.Name_Local}}</td>
        <td>{{item.Name_Common}}</td>
        <td>
            <td>
                <form action="" method="POST">
                    <!-- {% csrf_token %} -->
                    <input type="hidden" name="item_id" value="{{fine}}" />
                    <input type="submit" value="delete item">
                </form>
            </td>
        </td>
    </tr>
    {% endfor %}
</table>

templates/sea/fikiri.html
<!-- {{ items }} {{ think }} -->
<h1>Fish Site Query</h1>

<body style="background-color: aqua">
    <form style="margin-left:80px">
        Site Name: <input list="site_name">
        <datalist id="site_name">
        {% for i in items %}
            <option>
                {{ i.SiteName }}
            </option>
        {% endfor %}
        </datalist>
        <br> Fish Type: <input list="fish_type" style="margin-top: 20px">
        <datalist id="fish_type">
        {% for i in think %}
            <option>
                {{ i.Name_Local }}
            </option>
        {% endfor %}
        </datalist>
        <br> Start Date: <input type="date" name="start_date" style="margin-top: 20px">
        <br> End Date: <input type="date" name="end_date" style="margin-top: 20px">
        <br>
        <input type="submit" name="submit" value="Run Query" style="margin-top: 20px">
        <input type="button" name="ok" value="Exit" style="margin-top: 20px">
        <input type="reset" name="reset" value="Reset" style="margin-top: 20px">
    </form>
</body>

templates/sea/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>{% block title %}
    <h1><strong>MARINE ECOSYSTEM.</strong></h1> {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'sea/style.css' %}">
</head>

<body>
    <p>Hey! look, we finally have a homepage. it was Brian's idea, he was tired of working on "updating-tables" thingy. we hope it's pleasant enough. at leastfor now. we're worn out af. we'll work on the pimping some other day. our designs are really awful.
        we'll be attending architecture classes as from tomorrow. see ya1</p>
    <ul>
        <h2>Data addition links.</h2>
        <li>
            <a href="{% url 'sea:input' %}">Lookup fish.</a>

        </li>
        <li>
            <a href="{% url 'sea:input1' %}">lookup invert</a>

        </li>
        <li>
            <a href="{% url 'sea:input2' %}">Lookup benthic.</a>

        </li>
        <li>
            <a href="{% url 'sea:input3' %}">Benthic Survey</a>

        </li>
        <li>
            <a href="{% url 'sea:input4' %}">Fish survey.</a>

        </li>
        <li>
            <a href="{% url 'sea:input5' %}">Invert data.</a>

        </li>
        <li>
            <a href="{% url 'sea:input6' %}">Lookup site.</a>

        </li>
        <li>
            <a href="{% url 'sea:input7' %}">Survey info.</a>

        </li>
    </ul>

    <ul>
        <h2>Queries lists.</h2>
        <li>
            <a href="{% url 'sea:think' %}">Fish site query.</a>

        </li>
        <li>
            <a href="{% url 'sea:stuffs' %}">Invert site query.</a>

        </li>
        <li>
            <a href="{% url 'sea:lastone' %}">Benthic site query.</a>

        </li>

    </ul>




    {% block body %} {% endblock %}
</body>

</html>

templates/sea/input.html
<table>
    <h1>lookup fish data add form.</h1>
    <h2>Existing data.</h2>
    <thead>
        <tr>
            <th>Local Name</th>
            <th>Common name</th>
            <th>ID</th>
        </tr>
    </thead>
    <tbody>
        {% csrf_token %} {% for item in trial %}
        <tr class="datarow">
            <td>{{item.Name_Local}}</td>
            <td>{{item.Name_Common}}</td>
            <td>{{item.ID}}</td>

        </tr>
        {% endfor %}
    </tbody>
</table>




<body style="background-color: aquamarine">

    <table>
        <h3>Addition form.</h3>
        {% csrf_token %}
        <tr>
            <form action="" method="post">
                {% csrf_token %}
                <td>{{form.Name_Local}}</td>
                <td>{{form.Name_Common}}</td>
                <td>{{form.ID}}</td>
                <td> <input class="table_button" type="submit" value="Add inventory" /></td>
                <td> <input class="table_button" type="reset" value="Reset" /></td>
            </form>
            </td>
        </tr>
        <thead>
            <tr>
                <td>
                    <p>Local Name</p>
                </td>
                <td>
                    <p>Common Name </p>
                </td>
                <td>
                    <p>ID</p>
                </td>
                <td>
                    <p>Add</p>
                </td>
                <td>
                    <p>Reset</p>
                </td>
            </tr>
        </thead>

    </table>
</body>


<body style="background-color: aquamarine">

    <table>
        <h3>Deletion form.</h3>
        {% csrf_token %}
        <tr>
            <form action="delete" method="post">
                {% csrf_token %}
                <td>{{form.Name_Local}}</td>
                <td>{{form.Name_Common}}</td>
                <td>{{form.ID}}</td>
                <td> <input class="table_button" type="submit" value="Delete" /></td>
                <td> <input class="table_button" type="reset" value="Reset" /></td>
            </form>
            </td>
        </tr>
        <thead>
            <tr>
                <td>
                    <p>Local Name</p>
                </td>
                <td>
                    <p>Common Name </p>
                </td>
                <td>
                    <p>ID</p>
                </td>
                <td>
                    <p>Add</p>
                </td>
                <td>
                    <p>Reset</p>
                </td>
            </tr>
        </thead>

    </table>

templates/sea/input1.html
<!-- {{ trial }} -->
<table>
    <h1>lookup invert data add form.</h1>
    <h2>Existing data.</h2>
    <thead>
        <tr>
            <th>local name</th>
            <th>common name</th>
            <th>ID</th>
        </tr>
    </thead>
    <tbody>
        {% csrf_token %} {% for item in trial1 %}
        <tr class="datarow">
            <td>{{item.Name_Local}}</td>
            <td>{{item.Name_Common}}</td>
            <td>{{item.ID}}</td>

        </tr>
        {% endfor %}
    </tbody>

</table>



<!-- {{ form }} -->

<body style="background-color: aquamarine">

    <table>
        <h3>Addition form.</h3>
        {% csrf_token %}
        <tr>
            <form action="" method="post">
                {% csrf_token %}
                <td>{{form.Name_Local}}</td>
                <td>{{form.Name_Common}}</td>
                <td>{{form.ID}}</td>
                <td> <input class="table_button" type="submit" value="Add inventory" /></td>
                <td> <input class="table_button" type="reset" value="Reset" /></td>
            </form>
            </td>
        </tr>
        <thead>
            <tr>
                <td>
                    <p>Local Name</p>
                </td>
                <td>
                    <p>Common Name </p>
                </td>
                <td>
                    <p>ID</p>
                </td>
                <td>
                    <p>Add</p>
                </td>
                <td>
                    <p>Reset</p>
                </td>
            </tr>
        </thead>



    </table>
</body>

templates/sea/input2.html
<!-- {{ trial2 }} -->
<table>
    <h1>lookup Benthic data add form.</h1>
    <h3>Existing data.</h3>
    <thead>
        <tr>
            <th>local name</th>
            <th>Abbreviation.</th>
            <th>common name</th>
            <th>ID</th>
        </tr>
    </thead>
    <tbody>
        {% csrf_token %} {% for item in trial2 %}
        <tr class="datarow">
            <td>{{item.Name_Local}}</td>
            <td>{{item.Abbrv}}</td>
            <td>{{item.Name_Common}}</td>
            <td>{{item.ID}}</td>

        </tr>
        {% endfor %}</tbody>
</table>


<!-- {{ form }} -->

<body style="background-color: aquamarine">

    <table>
        <h3>Addition form.</h3>
        {% csrf_token %}
        <tr>
            <form action="" method="post">
                {% csrf_token %}
                <td>{{form.Name_Local}}</td>
                <td>{{form.Abbrv}}</td>
                <td>{{form.Name_Common}}</td>
                <td>{{form.ID}}</td>
                <td> <input class="table_button" type="submit" value="Add inventory" /></td>
                <td> <input class="table_button" type="reset" value="Reset" /></td>
            </form>
            </td>
        </tr>
        <thead>
            <tr>
                <td>
                    <p>Local Name</p>
                </td>
                <td>
                    <p>Abbreviation </p>
                </td>
                <td>
                    <p>Common Name </p>
                </td>
                <td>
                    <p>ID</p>
                </td>
                <td>
                    <p>Add</p>
                </td>
                <td>
                    <p>Reset</p>
                </td>
            </tr>
        </thead>
        <!-- {% for item in inventory %}
            <tr class="datarow">
                <td>{{item.quantity}}</td>
                <td>{{item.needs_repairs}}</td>
                <td>
                    <td>
                        <form action="/remove_items/" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="item_id" value="{{item.id}}" />
                            <input type="submit" value="delete item">
                        </form>
                    </td>
                </td>
            </tr>
            {% endfor %} -->
    </table>
</body>

templates/sea/input3.html
<!-- {{ trial3 }} -->
<!-- <table>
    <h1>lookup invert data add form.</h1>
    <h3>Existing data.</h3>
    {% csrf_token %} {% for item in trial3 %}
    <thead>
        <tr>
            <th>Transect ID</th>
            <th>Benthic category</th>
            <th>Total cover</th>
            <th>Change</th>
        </tr>
    </thead>
    <tbody>
        <tr class="datarow">
            <td>{{item.Enter_transect_ID}}</td>
            <td>{{item.Enter_benthic_category}}</td>
            <td>{{item.Enter_total_cover}}</td>

        </tr>
    </tbody>
    {% endfor %}
</table> -->
<table style="margin-left:50px">
    <h1>lookup invert data add form.</h1>
    <h3>Existing data.</h3>
    <thead>
        <tr>
            <th>Transect ID</th>
            <th>Benthic category</th>
            <th>Total cover</th>
            <th>Change</th>
        </tr>
    </thead>
    <tbody>
        {% csrf_token %} {% for item in trial3 %}
        <tr>
            <td>{{item.Enter_transect_ID}}</td>
            <td>{{item.Enter_benthic_category}}</td>
            <td>{{item.Enter_total_cover}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- {{ form }} -->

<body style="background-color: aquamarine">

    <table>
        <h3>Addition form.</h3>
        {% csrf_token %}
        <tr>
            <form action="" method="post">
                {% csrf_token %}
                <td>{{form.Enter_transect_ID}}</td>
                <td>{{form.Enter_benthic_category}}</td>
                <td>{{form.Enter_total_cover}}</td>
                <td> <input class="table_button" type="submit" value="Add inventory" /></td>
                <td> <input class="table_button" type="reset" value="Reset" /></td>
            </form>
            </td>
        </tr>
        <thead>
            <tr>
                <td>
                    <p>Transect ID</p>
                </td>
                <td>
                    <p>Benthic category</p>
                </td>
                <td>
                    <p>Total cover</p>
                </td>
                <td>
                    <p>Add</p>
                </td>
                <td>
                    <p>Reset</p>
                </td>
            </tr>
        </thead>
        <!-- {% for item in inventory %}
            <tr class="datarow">
                <td>{{item.quantity}}</td>
                <td>{{item.needs_repairs}}</td>
                <td>
                    <td>
                        <form action="/remove_items/" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="item_id" value="{{item.id}}" />
                            <input type="submit" value="delete item">
                        </form>
                    </td>
                </td>
            </tr>
            {% endfor %} -->
    </table>
</body>

templates/sea/input4.html
<!-- {{ trial4 }} -->
<table>
    <h1>fish survey data add form.</h1>
    <h3>Existing data.</h3>
    <thead>
        <tr>
            <th>ID</th>
            <th>Trans ID.</th>
            <th>Local name</th>
            <th>total</th>
        </tr>
    </thead>
    <tbody>
        {% csrf_token %} {% for item in trial4 %}
        <tr class="datarow">
            <td>{{item.ID}}</td>
            <td>{{item.Trans_ID}}</td>
            <td>{{item.Name_Local}}</td>
            <td>{{item.Total_Count}}</td>

        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- {{ form }} -->

<body style="background-color: aquamarine">

    <table>
        <h3>Addition form.</h3>
        {% csrf_token %}
        <tr>
            <form action="" method="post">
                {% csrf_token %}
                <td>{{form.ID}}</td>
                <td>{{form.Trans_ID}}</td>
                <td>{{form.Name_Local}}</td>
                <td>{{form.Total_Count}}</td>
                <td> <input class="table_button" type="submit" value="Add inventory" /></td>
                <td> <input class="table_button" type="reset" value="Reset" /></td>
            </form>
            </td>
        </tr>
        <thead>
            <tr>
                <td>
                    <p>id</p>
                </td>
                <td>
                    <p>Trans ID </p>
                </td>
                <td>
                    <p>Local Name</p>
                </td>
                <td>
                    <p>Total count</p>
                </td>
                <td>
                    <p>Add</p>
                </td>
                <td>
                    <p>Reset</p>
                </td>
            </tr>
        </thead>
        <!-- {% for item in inventory %}
        <tr class="datarow">
            <td>{{item.quantity}}</td>
            <td>{{item.needs_repairs}}</td>
            <td>
                <td>
                    <form action="/remove_items/" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="item_id" value="{{item.id}}" />
                        <input type="submit" value="delete item">
                    </form>
                </td>
            </td>
        </tr>
        {% endfor %} -->
    </table>
</body>

templates/sea/input5.html
<!-- {{ trial5 }} -->
<table>
    <h1>Invertebrates data add form.</h1>
    <h3>Existing data.</h3>
    <thead>
        <tr>
            <th>Trans ID.</th>
            <th>Invertebrate name</th>
            <th>Numberl</th>
        </tr>
    </thead>
    <tbody>
        {% csrf_token %} {% for item in trial5 %}
        <tr class="datarow">
            <td>{{item.TransID}}</td>
            <td>{{item.Name_Invert}}</td>
            <td>{{item.No_Invert}}</td>

        </tr>
        {% endfor %}</tbody>
</table>
<!-- {{ form }} -->

<body style="background-color: aquamarine">

    <table>
        <h3>Addition form.</h3>
        {% csrf_token %}
        <tr>
            <form action="" method="post">
                {% csrf_token %}
                <td>{{form.TransID}}</td>
                <td>{{form.Name_Invert}}</td>
                <td>{{form.No_Invert}}</td>
                <td> <input class="table_button" type="submit" value="Add inventory" /></td>
                <td> <input class="table_button" type="reset" value="Reset" /></td>
            </form>
            </td>
        </tr>
        <thead>
            <tr>
                <td>
                    <p>TransID</p>
                </td>
                <td>
                    <p>Name Invert</p>
                </td>
                <td>
                    <p>Number Invert</p>
                </td>
                <td>
                    <p>Add</p>
                </td>
                <td>
                    <p>Reset</p>
                </td>
            </tr>
        </thead>
        <!-- {% for item in inventory %}
        <tr class="datarow">
            <td>{{item.quantity}}</td>
            <td>{{item.needs_repairs}}</td>
            <td>
                <td>
                    <form action="/remove_items/" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="item_id" value="{{item.id}}" />
                        <input type="submit" value="delete item">
                    </form>
                </td>
            </td>
        </tr>
        {% endfor %} -->
    </table>
</body>

templates/sea/phone.html
<!-- {{ lastone }} {{ balls }} -->
<h1>Fish Site Query</h1>

<body style="background-color: aqua">
    <form style="margin-left:80px">
        benthic Name Abbreviation: <input list="abbreviation">
        <datalist id="abbreviation">
        {% for i in lastone %}
            <option>
                {{ i.Abbrv }}{{ i.Name_Local }}
            </option>
        {% endfor %}
        </datalist>
        <br> Site Name: <input list="names" style="margin-top: 20px">
        <datalist id="names">
        {% for item in balls %}
            <option>
                {{ item.SiteName }}
            </option>
        {% endfor %}
        </datalist>
        <br> Start Date: <input type="date" name="start_date" style="margin-top: 20px">
        <br> End Date: <input type="date" name="end_date" style="margin-top: 20px">
        <br>
        <input type="submit" name="submit" value="Run Query" style="margin-top: 20px">
        <input type="button" name="ok" value="Exit" style="margin-top: 20px">
        <input type="reset" name="reset" value="Reset" style="margin-top: 20px">
    </form>
</body>